name: Deploy BookSearchAiDemo to Azure Web App

on:
  push:
    branches:
      - master  # or main, depending on your default branch name
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Azure CLI Action
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
          az webapp deployment source config-zip --resource-group YourResourceGroupName --name BookSearchAiDemo --src ${{ github.workspace }}/app.zip

    - name: Generate deployment package
      run: zip -r app.zip . -x '*.git*'

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'BookSearchAiDemo'
        slot-name: 'Production'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}