name: Deploy BookSearchAiDemo to Azure Web App

on:
  push:
    branches:
      - master  # or main, depending on your default branch name
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_0FD23041367E498DA6A09BF4DEA08CD9 }}
        tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_4897F4EE54A244689FEC731D32FB8B41 }}
        subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D4EB5AF38FB347058B1893957979BA46 }}

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'BookSearchAiDemo'
        slot-name: 'Production'