name: Deploy to Azure Web App

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Create deployment package
      run: zip -r deploy.zip . -x '*.git*'

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'BookSearchAiDemo'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: './deploy.zip'

    - name: Debug Information
      if: failure()
      run: |
        echo "App Name: BookSearchAiDemo"
        echo "Package Path: ./deploy.zip"
        ls -la